### PR TITLE
Add Tabi health drain + FNF HD Warning notes

### PR DESCRIPTION
**Pull request by ItzFireable**
you're welcome, i want others to suffer :>

warning notes are placed anywhere except for one (for testing purposes) and they are placed in the -1 to -9 area. health drain is a nerfed version of tabi due to not having a 150% limit.

### CODE REVIEW

**Comment by ItzFireable** [comment]
(there's also tricky loading code for testing purposes, will utilize it later to get rid of the lag at the start because of the sign)

**Comment by AlwaysMemer** [comment]
you actual jackass, you did it

**Comment by ItzFireable** [comment]
:)

**Comment by Sector03** [comment]
OH MY FUCKING GOD YOU MAD MAN

**Pull request merged**
